### ISSUE TITLE
Missing ChromaHUD.java

### ISSUE THREAD

**Issue by lowercasebtw** [chetan0402/ChromaHUD#1]
Missing ChromaHUD.java, do you still have it?

**Comment by lowercasebtw** [comment]
just got it out of the jar with a java dcmplr

**Comment by chetan0402** [comment]
what the main file is missing?

**Comment by chetan0402** [comment]
Ah .gitignore removed it as ChromaHUD.java is true for ChromaHUD.* i was just trying to remove idea project files used to the wrong way to do that should have *.ipr instead

**Comment by chetan0402** [comment]
> just got it out of the jar with a java dcmplr

can u create a pull request to add it here cause i dont have the project on my laptop anymore
